### ISSUE TITLE
Ajustes de bugs encontrado en el modulo de catalogo de elemento y modulo de actas por parte de la analista 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#469]
Se debe ajustar los bug definidos en el [documento](https://docs.google.com/spreadsheets/d/17CFV1g-VUn5a8k6zf3sXx31OACPeu07vFsa_tph-gV4/edit?usp=sharing_eip&ts=600b300d&urp=gmail_link&gxids=7628) por parte de la analista de requerimientos @mcrubianot, también se anexa el [acta](https://docs.google.com/document/d/1frSJ855LFnarGyblU467H8XY80IIIe4C8ph05oLkVlA/edit?ts=600f4542) donde se socializo los errores, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar los bugs definidos en el documentos - [Ir a Bugs](#issuecomment-768785953)
- [x] Documentar los arreglos

**Comment by AlexFBP** [comment]
Se empieza a abordar el Issue

**Comment by AlexFBP** [comment]
![image](https://user-images.githubusercontent.com/6588872/105994328-7f699c80-6075-11eb-907f-ef6e576c6940.png)

1. Se agregó título a Catálogo de Elementos > Lista de Catálogos
2. Se corrigió la funcionalidad del boton de Agregar Catálogo
3. Se actualizaron los íconos de las acciones y se agregaron descripciones que aparecen al colocar el mouse encima

**Comment by AlexFBP** [comment]
Agregado título en Catálogo Elementos > Crear Catalogo, vista que abre no solo al crear sino al editar:

- Al crear:
  ![image](https://user-images.githubusercontent.com/6588872/106004689-75e63180-6081-11eb-9a0e-089e45fb872e.png)

- Al editar:
  ![image](https://user-images.githubusercontent.com/6588872/106004730-83032080-6081-11eb-9e82-6cf90afd8acc.png)

También se agregó un botón para volver a la lista, que se muestra solo al editar un catalogo:
![image](https://user-images.githubusercontent.com/6588872/106005967-bf834c00-6082-11eb-9ddf-8ca9593e3a5c.png)

**Comment by AlexFBP** [comment]
En Catalogo de Elementos > Consultar Catalogo, se agregó un spinner mientras carga la lista de catálogos
![image](https://user-images.githubusercontent.com/6588872/106009549-733a0b00-6086-11eb-857b-82768d916aa8.png)

**Comment by AlexFBP** [comment]
A modo de referencia, se traen los Issues anotados del acta/grabación:

### Modulo Catalogo de Elementos

- [ ] Revisar acción :eye: en Consultar/construir catalogo/etc... (Eliminar la acción " :eye: " donde sea posible o agregar una mejor descripción de lo que hace)
- [ ] Colocar un indicador de carga en construccion catalogo
- [ ] Agregar spinners en casi todo lado...
- [ ] En Asignación de cuentas, ocultar detalle cuando se seleccione algo que **no** sea una Clase
- [ ] Revisar traducciones en asignación de cuentas

### Modulo de Actas de Recibido

- [x] #467 Al editar un acta, el revisor/contratista está "quemado" en "Nilson"
- [ ] Spinner en carga masiva
- [ ] Revisar cálculos de IVA, Descuento (en MID? en el Cliente?)
- [ ] De la tabla de Elementos, seleccionar/autocompletar no solo por nombre sino por código
- [x] #468 Ajustar comportamiento del botón de guardar acta

### De la parte contable (Catalogo > Asignar cuentas)
- [ ] _"Descuentos no esta funcionando a nivel de cliente"_ Agregar spinner y verificar sumas después de carga masiva (a veces funciona, a veces no)
- [ ] _"Cuentas Contables no esta dejando hacer put, si hace get y post, tambien hay un problema con depreciación no se sabe aun"_ Agregar cuentas, al seleccionar la clase trae las cuentas existentes, al asignar las cuentas a una clase que no las tenía, funciona (el POST funciona) pero al actualizar cuentas, no (falla el PUT)

**Comment by AlexFBP** [comment]
El Issue aún no está completo

**Comment by AlexFBP** [comment]
Prioridad: Mejorar la UX:
- Colocar instrucciones sobre cómo usar los árboles y las acciones

**Comment by AlexFBP** [comment]
En #461 faltó actualizar los nombres de cuentas en Catálogo > Asignación, lo cual ya se arregló.

![image](https://user-images.githubusercontent.com/6588872/106298446-e461f580-6221-11eb-8cdd-078acec65cdc.png)

Solo queda pendiente la entrada "EBEMP", lo cual se corregirá automáticamente una vez se aplique el PR #476

**Comment by AlexFBP** [comment]
En las vistas del módulo "Catálogo de Elementos", donde se consuma el arbol:
1. Los iconos de expandir/colapsar un nivel (cualquiera) del catálogo, solamente se muestran si esto tiene sentido, es decir, cuando el elemento actual tenga elementos hijos. Adicionalmente, se cambiaron los íconos para hacerlos más notorios y se agregaron "tooltip" que aparecen al pasar el mouse encima:
   ![image](https://user-images.githubusercontent.com/6588872/106402631-5ee46e00-63f8-11eb-9976-f3da773af1f9.png)
   ![image](https://user-images.githubusercontent.com/6588872/106402658-83404a80-63f8-11eb-8d44-6451596b7fa5.png)

   Por lo anterior, **_se desactivó que se pueda desplegar/colapsar el arbol haciendo click en cualquier parte de la fila_** (aunque esto último se puede deshacer). Únicamente quedó el evento que se genera al hacer click en la fila, que se usa (por ejemplo) en "construcción de Catálogo"
2. Se actualizaron los íconos que indican la columna por la que se están ordenando los resultados, y en qué orden se está haciendo:
   ![image](https://user-images.githubusercontent.com/6588872/106402766-22654200-63f9-11eb-9c1b-2f40c272fdae.png)
3. Se cambió el ícono de las acciones, y se le agregó un "tooltip". Adicionalmente se hizo paramétrico: solo se muestra si una vista que consume el árbol, lo requiere. En el momento solo se marcó requerido en la vista de "Consultar Catálogo":
   ![image](https://user-images.githubusercontent.com/6588872/106403110-e8953b00-63fa-11eb-84b5-9f6019814ad0.png)
   
4. Al hacer click, después de un tiempo aparecía una información asociada que antes tapaba la tabla, ahora se muestra dicha información en un diálogo (con spinner de carga):
   ![image](https://user-images.githubusercontent.com/6588872/106403210-6bb69100-63fb-11eb-92e3-27a278f07e2d.png)
   ![image](https://user-images.githubusercontent.com/6588872/106403151-26925f00-63fb-11eb-931a-6aba7014ee61.png)

**Comment by AlexFBP** [comment]
- Cuando se use [dynamic-form](https://github.com/udistrital/arka_cliente/tree/dev/src/app/%40theme/components/dinamicform) y campos tipo radio o checkbox, faltaba colocar una indicación que se muestre si el campo debía llenarse y no se llenó. Específicamente para la creación de catálogos:
  ![image](https://user-images.githubusercontent.com/6588872/106705685-68b6ce80-65bc-11eb-8ffb-5fc8ec317486.png)

- Se agregaron indicaciones para llenar las cuentas contables 
  ![image](https://user-images.githubusercontent.com/6588872/106705797-a156a800-65bc-11eb-8861-86d5a16899fb.png)

- La UX en la parte de inactivar niveles (grupos/subgrupos) se refactorizó para simplemente mostrar un dialogo de confirmación con el nivel a inactivar. Esto porque el formulario de la derecha no mostraba más información de la que había en la tabla, y en cambio si se usaba otra petición (innecesaria también) para llenarlo.
  ![image](https://user-images.githubusercontent.com/6588872/106706226-5a1ce700-65bd-11eb-8626-5c4b67da3997.png)

  Asociado a esto (pero independiente a este refactor), también se quitó una petición sin usar, a la API CRUD de Catalogo

- Se arregló un bug de un movimiento no encontrado que se quedaba siempre cargando...
- Se quitaron algunas etiquetas div innecesarias
- Para ahorrar recursos de red, algunas peticiones innecesarias se quitaron

**Comment by AlexFBP** [comment]
Se agregó un diálogo de confirmación si se detecta que hay elementos previamente cargados
![image](https://user-images.githubusercontent.com/6588872/107473786-39b1d700-6b3f-11eb-83ca-b2a0d96c07f1.png)

Adicionalmente, se agregaron indicadores de carga tanto al hacer carga masiva, como al guardar/enviar un acta

**Comment by AlexFBP** [comment]
Excepto en la lista de catálogos, para las demás secciones (desde construcción de catálogo en más) se muestran solamente catálogos activos

**Comment by AlexFBP** [comment]
Hay otros bugs adicionales mencionados en [el documento](https://docs.google.com/spreadsheets/d/17CFV1g-VUn5a8k6zf3sXx31OACPeu07vFsa_tph-gV4/), no contemplados [arriba](#issuecomment-768785953):

(*): Por validar

Probar con el Acta 65

## Módulo de Actas

### Consulta de un acta en estado "En Verificación"
- [x] 3a6b51b En verificación, actas sin elementos se quedan procesando
- [ ] "_Se consulta un acta anulada: El sistema alerta que la opción no es válida. pero debería permitirme verla así esté anulada_" - Aclarar en el diálogo que para ver un acta hay que dar click en la fila, y colocar instrucciones antes de la tabla O, restablecer parte del comportamiento antes de #344 (agregando el :eye:)
- [ ] "_En la verificación se revisa el registro y se observa que los cálculos de los valores no se están haciendo correctamente (valor subtotal menos descuentos debe dar cero y etá trayendo el mismo valor del subtotal, adicional hace un cálculo de un iva cuando el porcentaje es 0 y por consiguiente da un total que no debería mostrarse)..._" - Verificar los cálculos en "Validación"
- [ ] "_...si le damos al botón de Verificar, se genera el proceso sin validar lo anterior._" - Validar la validación...
- [ ] Gran subtotal se muestra en ceros, revisar visualización

### Registro de Acta de Recibido
- [x] (*) "_La plantilla que se tiene no está haciendo la sumatoria correspondiente al descuento y por consiguiente al sacar los valores totales tampoco_"
- [x] (*) "_Se procede a seleccionar los bienes para asignar la clase pero el link donde me los debe mostrar no me trae nada_"
- [x] (*) "_no está trayendo la sumatoria de los descuentos_"
- [ ] "_No tiene ningun tipo de validación o notificación al usuario de que no cuenta con este registro_" - Verificar que el envío a revisor se habilite únicamente si están asignadas las clases a los elementos

### Registro de Acta Especial
- [x] (*) "_no está trayendo parámetros para diligenciar del proveedor y factura_"
- [ ] "_Cargo archivo de elementos y sin colocar la clase a la que pertenecen y el tipo de bien y la deja registrar_" - Validar que se permita ingresar las clases
- [x] (*) "_Al seleccionar la clase de bien, no lo está trayendo_"

### Consulta de Acta (ver)
- [ ] "_El acta de recibido pasó por todos los procesos, pero ... el porcentaje del iva aplicado no es el mismo que se define en la plantilla_" - Revisar visualización de porcentajes de IVA
- [ ] Revisar visualización de subtotales
- [ ] "_No está trayendo la clase definida para la elaboración del acta No.65_" - Revisar visualización de clases de elementos
- [ ] Articulos/Elementos carga varias veces, quitar parpadeo

## Módulo de Entradas

### Registrar Entrada
- [ ] "_Revisor y ubicación que está trayendo datos en la consulta del acta de recibido para la entrada, diferenten al listado del acta de recibido_" - Corregir visualización en la lista de actas disponibles para registrar una entrada:
      - Resolver el ID del Revisor (mostrar el nombre, no el ID)
      - Para la ubicación, cambiar en "Acta Recibido > Consulta de Actas" el título de la columna "Ubicación" por "Dependencia"

### Consulta de Entradas
- [ ] "_Se hace la consulta sobre el id 65 de la entrada registrada y me muestra datos que no concuerdan con el actad e recibido, por que me muestra un acta de recibido No.7 (cuando la que se está trabajando es la 65)_" - La columna ID corresponde al ID de la entrada en la base de datos, lo cual se presta para confusiones:
      - ocultar la columna de ID (el IDentificador suficiente/necesario debería ser el Consecutivo)
      - (opcional) Mover la columna de Acta Recibido al comienzo
- [ ] "_Se hace la consulta sobre el id 65 del acta de recibido y me trae el consecutivo de la entrada id 247 (cuado realmente cuando me la genera me  muestra el No. de entrada 65)_" - Es consecuencia del anterior...
- [ ] "_Se consulta la entrada en reporte y no está trayendo toda la información_" - Revisar reportes...

En relación a este mensaje, puede ser necesario reabrir este Issue y/o crear uno o más Issues adicionales
