### ISSUE TITLE
Ajustes pendientes de bugs encontrado en el modulo de actas de recibido y modulo de entradas  por parte de la analista 

### ISSUE THREAD

**Issue by fabianbarreto02** [udistrital/arka_cliente#505]
Se debe ajustar los bug que aun quedan pendientes y del modulo de entradas definidos en el [documento](https://docs.google.com/spreadsheets/d/17CFV1g-VUn5a8k6zf3sXx31OACPeu07vFsa_tph-gV4/edit?usp=sharing_eip&ts=600b300d&urp=gmail_link&gxids=7628) por parte de la analista de requerimientos @mcrubianot, también se anexa el [acta](https://docs.google.com/document/d/1frSJ855LFnarGyblU467H8XY80IIIe4C8ph05oLkVlA/edit?ts=600f4542) donde se socializo los errores, la issue debe cumplir con los siguientes requerimientos:

- [x] Ajustar los bugs definidos en el documentos 
- [x] Documentar los ajustes en el formato aplicación de pruebas

**Comment by AlexFBP** [comment]
A modo de referencia, se trae de #469 los [bugs faltantes](https://github.com/udistrital/arka_cliente/issues/469#issuecomment-776809824):

(*): Por validar

Probar con el Acta 65 y luego con el Acta 63
En _cursiva_ extractos del documento

## Módulo de Actas

### Consulta de un acta en estado "En Verificación"
- [x] #501 En verificación, actas sin elementos se quedan procesando
- [ ] "_Se consulta un acta anulada: El sistema alerta que la opción no es válida. pero debería permitirme verla así esté anulada_" - Aclarar en el diálogo que para ver un acta hay que dar click en la fila, y colocar instrucciones antes de la tabla O, restablecer parte del comportamiento antes de #344 (agregando el :eye:)
- [ ] "_En la verificación se revisa el registro y se observa que los cálculos de los valores no se están haciendo correctamente (valor subtotal menos descuentos debe dar cero y etá trayendo el mismo valor del subtotal, adicional hace un cálculo de un iva cuando el porcentaje es 0 y por consiguiente da un total que no debería mostrarse)..._" - Verificar los cálculos en "Validación"
- [ ] "_...si le damos al botón de Verificar, se genera el proceso sin validar lo anterior._" - Validar la validación...
- [ ] Gran subtotal se muestra en ceros, revisar visualización

### Registro de Acta de Recibido
- [x] (*) "_La plantilla que se tiene no está haciendo la sumatoria correspondiente al descuento y por consiguiente al sacar los valores totales tampoco_"
- [x] (*) "_Se procede a seleccionar los bienes para asignar la clase pero el link donde me los debe mostrar no me trae nada_"
- [x] (*) "_no está trayendo la sumatoria de los descuentos_"
- [ ] "_No tiene ningun tipo de validación o notificación al usuario de que no cuenta con este registro_" - Verificar que el envío a revisor se habilite únicamente si están asignadas las clases a los elementos

### Registro de Acta Especial
- [x] (*) "_no está trayendo parámetros para diligenciar del proveedor y factura_"
- [ ] "_Cargo archivo de elementos y sin colocar la clase a la que pertenecen y el tipo de bien y la deja registrar_" - Validar que se permita ingresar las clases, y que todos los objetos tengan su clase asignada.
- [x] (*) "_Al seleccionar la clase de bien, no lo está trayendo_"

### Consulta de Acta (ver)
- [ ] "_El acta de recibido pasó por todos los procesos, pero ... el porcentaje del iva aplicado no es el mismo que se define en la plantilla_" - Revisar visualización/cálculo de porcentajes de IVA
- [ ] Revisar visualización/cálculo de subtotales
- [ ] "_No está trayendo la clase definida para la elaboración del acta No.65_" - Revisar visualización de clases de elementos
- [x] #501 Articulos/Elementos carga varias veces, quitar parpadeo

## Módulo de Entradas

### Registrar Entrada
- [ ] "_Revisor y ubicación que está trayendo datos en la consulta del acta de recibido para la entrada, diferenten al listado del acta de recibido_" - Corregir visualización en la lista de actas disponibles para registrar una entrada:
      - Resolver el ID del Revisor (mostrar el nombre, no el ID)
      - Para la ubicación, cambiar en "Acta Recibido > Consulta de Actas" el título de la columna "Ubicación" por "Dependencia"

### Consulta de Entradas
- [ ] "_Se hace la consulta sobre el id 65 de la entrada registrada y me muestra datos que no concuerdan con el actad e recibido, por que me muestra un acta de recibido No.7 (cuando la que se está trabajando es la 65)_" - La columna ID corresponde al ID de la entrada en la base de datos, lo cual se presta para confusiones:
      - ocultar la columna de ID (el IDentificador suficiente/necesario debería ser el Consecutivo)
      - (opcional) Mover la columna de Acta Recibido al comienzo
- [ ] "_Se hace la consulta sobre el id 65 del acta de recibido y me trae el consecutivo de la entrada id 247 (cuado realmente cuando me la genera me  muestra el No. de entrada 65)_" - Es consecuencia del anterior...
- [ ] "_Se consulta la entrada en reporte y no está trayendo toda la información_" - Revisar reportes...

En relación a este mensaje, puede ser necesario reabrir este Issue y/o crear uno o más Issues adicionales

**Comment by AlexFBP** [comment]
Se agregan instrucciones adicionales al comienzo de la lista de actas:
![image](https://user-images.githubusercontent.com/6588872/107989661-b78f3b80-6fa0-11eb-9267-6c5fffbe5d41.png)

Y se aclara el mensaje que se muestra cuando un acta no se puede editar (de manera similar a cuando no se puede anular):
![image](https://user-images.githubusercontent.com/6588872/107989713-d68dcd80-6fa0-11eb-99ee-29bb8f90bfb2.png)

**Comment by AlexFBP** [comment]
Se aclaran las personas involucradas en un acta, sobretodo el contratista:

- En consulta de Actas
  ![image](https://user-images.githubusercontent.com/6588872/108298779-8151e780-716b-11eb-89e8-afa132f02730.png)
- Al editar un acta en estado Registrada
  ![image](https://user-images.githubusercontent.com/6588872/108298621-43ed5a00-716b-11eb-98e7-f75be594772a.png)
- Al editar/registrar un acta:
  ![image](https://user-images.githubusercontent.com/6588872/108298525-1bfdf680-716b-11eb-8049-8c2f5e192454.png)

**Comment by AlexFBP** [comment]
En la lista de actas, se agregó una columna para mostrar quién aceptó un acta:
![image](https://user-images.githubusercontent.com/6588872/108303128-54a1ce00-7173-11eb-8dbf-4cba900504bc.png)

Esta funcionalidad se está haciendo (provisionalmente) desde el cliente. Lo ideal es que, así como el MID retorna la fecha de aprobación, que retornara la persona asociada a dicha fecha.

**Comment by AlexFBP** [comment]
Respecto a los bugs:

> ### Consulta de Acta (ver)
> - [ ] "_El acta de recibido pasó por todos los procesos, pero ... el porcentaje del iva aplicado no es el mismo que se define en la plantilla_" - **Revisar visualización/cálculo de porcentajes de IVA**
> - [ ] Revisar visualización/cálculo de subtotales
> ### Consulta de Entradas
> - [ ] "_Se consulta la entrada en reporte y no está trayendo toda la información_" - Revisar reportes...

Se concluyó en el Daily de hoy, que se creará otro _Issue_ para abordar el cálculo desde el MID o el cliente, de los valores que se puedan calcular, asociados a cada elemento:
- Subtotales
- Valor IVA
- Totales

**Comment by AlexFBP** [comment]
Se actualizó el [documento de hallazgos](https://docs.google.com/spreadsheets/d/17CFV1g-VUn5a8k6zf3sXx31OACPeu07vFsa_tph-gV4/edit?ts=600b300d#gid=1378039263), con la salvedad [mencionada](#issuecomment-781465282) anteriormente

**Comment by AlexFBP** [comment]
Con fines de UX, se agregó a la UI una indicación de la razón del por qué está desactivado el botón de envío de un Acta a Verificación:

![image](https://user-images.githubusercontent.com/6588872/108603476-0a3c6f00-7376-11eb-9bea-a2a865707b0a.png)

**Comment by fabianbarreto02** [comment]
se da

**Comment by fabianbarreto02** [comment]
Se d por finalizada la issue
