### ISSUE TITLE
Revisar/Ajustar Consulta de Kardex

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#599]
Leyenda:
Rojo: Agregar - Azul: Quitar - Negro: Comentarios

![image](https://user-images.githubusercontent.com/6588872/126909103-6c977f92-df81-45f0-83ff-8c1dc80ca36f.png)

- [x] La columna "Consecutivo" tiene sentido? Revisar si es necesaria (Confirmar con Analista), si no, quitarla - Tendrá que ver con el consecutivo de la Salida? #672 ?
- [x] La columna "Observaciones" tiene sentido? De donde se construye? Del primer elemento con el que se abre la ficha Kardex? O se le puede crear una observación a toda una ficha Kardex? - Confirmar con Analista. Si la observación debería ser para toda la ficha, debería considerarase en #600 también
- [x] Confirmar con Analista si en la tabla de Consulta de Kardex, en vez de las columnas anteriores de pronto haga falta más bien agregar una o más columnas que contengan la clasificación de catálogo asociada
- [x] Agregar columna para mostrar el saldo
- [x] Cambiar titulo de la columna "Detalle" por "Acciones"
- [x] Agregar un tooltip al :eye: que diga "Detalle" o "Ver" (aprovechar la i18n ya existente)
- [x] Agregar la acción de editar, y agregar una vista vacía para más adelante poder implementar #600
- [x] Actualizar endpoint del MID (de ser necesario)
- [x] Actualizar cliente

**Comment by AlexFBP** [comment]
@mcrubianot podrías revisar cómo proceder con los 3 primeros?

**Comment by mcrubianot** [comment]
La columna "Consecutivo" tiene sentido? Revisar si es necesaria (Confirmar con Analista), si no, quitarla - Tendrá que ver con el consecutivo de la Salida? Mostrar consecutivo asignado a Salida #672 ?

Cuando se realizó el análisis se consideró que el consecutivo era el dado a la tarjeta de Kardex como tal, nada tiene que ver con ni con las salidas ni con las entradas

 La columna "Observaciones" tiene sentido? De donde se construye? Del primer elemento con el que se abre la ficha Kardex? O se le puede crear una observación a toda una ficha Kardex? - Confirmar con Analista. Si la observación debería ser para toda la ficha, debería considerarase en Permitir editar Maximos/Minimos de fichas Kardex #600 también

No recuerdo que hubiésemos definido nada con respecto a esta columna, preferible crear una observación dentro de la ficha

Confirmar con Analista si en la tabla de Consulta de Kardex, en vez de las columnas anteriores de pronto haga falta más bien agregar una o más columnas que contengan la clasificación de catálogo asociada

Considero entonces quitar la columna de observaciones e incluir la clasificación del bien
