### ISSUE TITLE
Levantamiento de Issues, Estado actual

### ISSUE THREAD

**Issue by AlexFBP** [udistrital/arka_cliente#695]
Para sacar issues:
- [x] [Levantamiento Requerimientos Julio 13](https://drive.google.com/file/d/1jw3QyQdrI2y89a79kz39vWeqWde5RD7U/view)
- [x] [Exposición Julio 15 a Viviana](https://drive.google.com/file/d/1Ok8H-aOmtHuSXmnZ0wzosOC9apcdjUDj/view)

_Originally posted by @AlexFBP in https://github.com/udistrital/arka_cliente/issues/641#issuecomment-881005320_

**Comment by AlexFBP** [comment]
(NOTA: Un :white_check_mark: significa que ya se describe en un Issue)
De la mesa del 13 de Julio se observan los siguientes:

Acta Recibido, Registro
- [ ] 20:45 - Contratista no carga - #680 

Acta Recibido, Edición
- [ ] 23:06 - Estado Registrada: Cambiar el nombre del primer estado a las Actas, de "Registrada" a otro, "Borrador", "Iniciada" (Confirmar con MariaC y Almacén)
- [ ] 24:19 - Paso 3: mostrar consolidado solamente si hay elementos cargados
- [ ] 24:40 y 39:29 - Estado Registrada, En Elaboración: Después de enviar al proveedor (y posiblemente también pasa con el contratista) o a verificación, se observa que el acta fue enviada pero luego salió un Error 400... Asegurarse que no siga saliendo
- [ ] 24:52 - Donde aparezca "Contratista", cambiar por "Auxiliar I" o "Auxiliar II" - #685, item 2
- [ ] 27:02 a 34:31 - Generalidades Anulación/Ajustes
- [ ] 34:50 - Mostrar Estado del Acta
- [ ] 38:33 - Después de asignar (clasificación) masivamente, mantener marcado el checkbox
- [ ] (No mostrado) - Para el soporte, justo al cargar el acta verificar si existe y en función de esto, actualizar el "ojo" de "ver soporte"

Acta Recibido, Validar
- [ ] 40:10 - Si no hay un soporte, no mostrar el ojo!. Alternativamente, cambiar el 404 por un aviso que explícitamente indique que no se encontró el soporte asociado.
- [ ] 40:30 - Cambiar texto botón "Verificar" por "Aprobar"
- [ ] 40:54 - El botón de verificar debería tener como condición OR para la deshabilitación, cuando el soporte tenga error o esté vacío
- [ ] (No mostrado) - Para el soporte, justo al cargar el acta verificar si existe y en función de esto, actualizar el "ojo" de "ver soporte"
- [ ] 41:05 - No se pueden rechazar actas...

Entradas, Registrar:
- [ ] 42:24 Muestra Error 502

**Comment by AlexFBP** [comment]
De la Exposición del 15 de Junio

Catalogo de Elementos > Registro
- [ ] (16) 6:22 - Quitar campos Fecha de Inicio (asegurar que se defina al momento del POST, y/o que es un campo completamente diferente al de Fecha de Creación); y quitar Fecha de Finalización (Eliminar completamente del modelo)

Catalogo > Inactivar Niveles
- [ ] (17) 9:47 - La vista Inactivar Niveles "no es efectiva". En el Arbol, agregar una columna Estado: Activo/Inactivo. Adicionalmente, al componente del arbol agregarle un parámetro que, de no especificarse o ser false (por defecto) oculte esta columna. Esto también se podría integrar con la vista de Construcción de Catálogo

Catálogo > ??
- [ ] (18) (No mencionado) - No hay forma de desactivar elementos! Falta desarrollar la funcionalidad asociada a esto (o revisar si es que ya está desarrollada pero de pronto oculta). Se sugiere trabajar esta funcionalidad en la vista de Registrar Elementos, hacer que la petición al MID se le pueda especificar un parámetro adicional para que en la jerarquía que retorna también traiga los elementos asociados

Catálogo > Asignación de Cuentas
- [ ] (19) 16:34 - Cuenta Débito para las Entradas debe ser la misma. Arreglo similar para las Salidas
- [ ] (20) 17:20 (No mencionado) - No tiene sentido el registro de cuentas para "Traslados", para traslados se usa la misma cuenta en la transacción (Confirmar con MariaC y Contabilidad)
- [x] (21) 18:32 - Mejorar consulta de Cuentas #694

Acta de Recibido
- [ ] (22) 22:39 (No mencionado) Agregar 2 estados más: "En Elaboración - Proveedor" y "En Elaboración - Contratista", que sean mutuamente excluyentes para bloquear el acceso... O en general, agregar "un campo", una mecánica de bloqueo, puede ser con una tabla de bloqueos (con campos ActaId y TerceroId) que se consulte para saber si un acta determinada está en edición y por quién

Acta de Recibido > Registro (de Acta Ordinaria)
- [ ] (23) (No mencionado) En las instrucciones, mostrar una lista de los tipos de entrada que se pueden hacer con este registro
- [x] (Duplicado del 1) 22:43 y 30:28 -  #680
- [x] (24) 25:17 -  #645 
- [ ] (25) 25:58 - (averiguar e) Indicar el peso máximo del (único) PDF, y que "el soporte debe ser un único PDF que combine todo". En la averiguación, identificar si pueden haber limitantes de las APIs en sí y/o por WSO2
- [ ] (26) 26:08 (No mencionado, mejora a medio/largo plazo a modelos) Mover el proveedor al Acta, y vincular los elementos al Acta en vez de al soporte, con el fin de permitir cargar varios soportes
- [ ] (27) 27:34 (No mencionado) - Revisar la validación del contratista, el botón de "Guardar Cambios" solo debería habilitarse si el contratista es válido (no debería permitirse tener simplemente cualquier valor)
- [ ] (28) 27:48 (con lo anterior) - Revisar si la API que recibe la transacción no está validando el formulario, o por qué se traba en este escenario, antes de empezar a corregir el anterior!
- [ ] (29) (No mencionado, mejora) - Intentar reutilizar el componente de Edición

Actas > Consultar
- [ ] (Duplicado de 2) 28:22 - Cambiar el nombre del primer estado de las actas
- [ ] (30) (No mencionado) - Hacer que desde el MID venga en el estado el estado ID (no el nombre), y ya desde el cliente se asocia el ID al i18n/L10n respectivo

Actas > Editar
- [x] (31, parecido al 1 y relacionable con el 29) 32:51, 48:43 y 52:44 -  #688 
- [ ] (32) 34:21 - Verificar y Disminuir las diferencias entre el "Guardar Cambios" y el "Enviar a", sobretodo en términos de peticiones a APIs y subida de soportes ==> Optimizacion: Hacer una única petición al MID (soportes + datos) y que el mismo MID haga el resto. O al menos reducir la cantidad de peticiones PUT/POST
- [ ] (Duplicado de 27 y 28) 37:48 - Envío a siguiente etapa (Registrada -> Elaboración) se queda cargando
- [ ] (33) 40:18 (No mencionado) - A la plantilla que se descarga, cargarle los "escenarios de prueba" (elementos con varias opciones de impuestos, etc) y mirar cómo se comporta
- [ ] (34) 45:24 - Tipos de bienes solo van a ser Devolutivo y Consumo, con (devolutivo?) de menor/mayor cuantía #681
- [ ] (35) 48:56 (No mencionado) 156 es Acta especial... en modificación? Dato técnico: Hacer que el id de las actas especiales no sea simplemente vacío, `0` o `null`, sino, ej, -1 (o verificar que el comportamiento actual sea similar, porque algunas actas de las que ya están, al ser enviadas y luego rechazadas, quedan como actas especiales y no se pueden volver a enviar...)... Mejor aún si se puede evitar el acta especial...
- [ ] (36) 53:47 (y donde aplique)... Indicar cuándo se deben ingresar más de _n_ letras para que aparezcan opciones
- [ ] (45) (No mencionado) En Captura de Elementos (manual o por carga masiva) restringir cantidad=1, unidad=UNIDAD cuando se especifique un serial

Actas > Registro (de Acta) Especial
- [ ] (Relacionado con 38) (No mencionado) En las instrucciones, indicar la lista de entradas a las que se podrá asociar este tipo de Acta
- [ ] (Relacionado con 35) (No mencionado) (Mejora) Para reducir el código duplicado, intentar reutilizar el componente de Edición de Acta para Registro de Actas (Ordinarias) y Actas Especiales

Entradas > Registrar
- [ ] (37) 56:04 Cambiar el icono por una flecha hacia la derecha, y en "Acciones" cambiarlo por "Registrar" o "Continuar" (según mejor se entienda)
- [ ] (38) 56:06 Una vez seleccionada el acta, en las instrucciones "Seleccione ..." terminar con "... de acuerdo a los tipos de entrada disponibles para el tipo de acta seleccionada", o cambiar la redacción de tal manera que se entienda que los tipos de entrada que se muestra son los que se pueden hacer para el tipo de acta seleccionada
- [ ] (39) 57:20 - El espacio del reporte sale vacío - #660.
- [ ] (40) 57:20 - Aparece 2 veces el consecutivo/número de la entrada, en el diálogo de "Entrada Registrada"

Salidas > Registrar
- [ ] (41) 1:01:32 - Selección de un rango de elementos a asignar con Click y Shift + Click, luego asignar funcionarios; no está funcionando adecuadamente ... La asignación no está teniendo en cuenta las casillas marcadas...
- [x] (42) 1:01:50 (No mencionado directamente) - Realizar un documento que consigne los datos de prueba, en este caso, sede/dependencia/ubicación y nombre del funcionario a quien se le asignaron los elementos. También indicar cual es el funcionario que se debe especificar para que los elementos de consumo se puedan enviar a bodega de consumo cuando no se asignen inmediatamente a un funcionario determinado #621
- [ ] (43) 1:02:45 (No mencionado) - Confirmar (con Analista y Almacén) si hay más de una bodega de consumo (ej, por sede), y tenerlo en cuenta para permitir tener una lista de los funcionarios a quienes se les podrá asignar (esto debería ser parametrizable). Este desplegable debería de habilitarse con un switch/deslizante. Si se toma un elemento de este desplegable (que inicialmente será quemado, pero posteriormente debería venir de una tabla de ajustes/parámetros) deberán actualizarse los demás campos y/o bloquearse (ubicación/sede/dependencia)
- [ ] (44) 1:04:10 - (No mencionado directamente) Aclarar las instrucciones de las observaciones, posiblemente en el _placeholder_
- [ ] (45) 1:05:11 - Una vez se finaliza el registro de la salida, no se está mostrando el consecutivo asignado a la salida en el diálogo de éxito

Bodega de Consumo > Asignación a Kardex
- [ ] (46) 1:06:10 - (No mencionado) En las instrucciones "Selecciona el tipo de Elemento del Catálogo...", agregar un renglón adicional que diga algo similar a "Se creará una nueva ficha Kardex si no ha sido creada previamente". De tal manera que, al dar en "Asociar", en la siguiente ventana hay que mostrar (no hay) instrucciones debajo de la sección que ahora se muestra. Por ejemplo, si ya había ficha, la sección que viene es "Asignación a Ficha Kardex Existente" pero no tiene instrucciones, las cuales podrían ser, de manera similar a la página anterior, algo como "Ya había una ficha Kardex para el tipo de elemento seleccionado.". Del mismo modo, agregar instrucciones (si no las hay) para cuando se detecte que no había ficha kardex
- [ ] (47) 1:08:17 - (No mencionado) De pronto falta mostrar el consecutivo de la entrada a kardex? Confirmar con Analista y/o Almacén

Bodega de Consumo > Consulta de Kardex
- [ ] (48) 1:08:25 - (No mencionado) Ajustar las columnas: "Consecutivo" y "Observaciones" pueden no ser necesarias (revisar), en cambio si falta/ayudaría mostrar la clasificación de catálogo en una o varias columnas, y en otra la cantidad actual
- [ ] (49) 1:08:28 - (No mencionado) Permitir cambiar los minimos y maximos por ficha Kardex Cambiar la columna "Detalle" por "Acciones", colocarle un tooltip al :eye: que diga "Detalle"
- [ ] (50) 1:08:36 - (No mencionado) Al ver una ficha Kardex, el detalle; permitir trabajar las fichas Kardex con un paginador y/o traer los registros por demanda (ej, los últimos 10 registros)

Bodega de Consumo > Solicitar Elementos
- [ ] (51) 1:08:56 - Falta la parte de roles-administrativa asociada a abrir la solicitudes. Actualmente tendrían que acercarse a Almacen con un formato o algo, y Almacén usaría el sistema...
- [ ] (52 - relacionado con 42 y la anterior) 1:09:59 - (No mencionado) Revisar si es necesario asignar sede/dependencia/ubicación, se podrían obtener del usuario actual, del solicitante...
- [ ] (53) 1:10:42 - Error 409, posiblemente por documento/usuario duplicado en terceros (409 es conflicto) --> Los usuarios que deberían poder seleccionarse no deberían tener conflicto, de todas maneras revisar

Bodega de Consumo > Consultar Solicitudes
- [ ] (Duplicado de 53) 1:11:10 - Error 409

Bodega de Consumo > Responder Solicitudes
- [ ] (Duplicado de 53) 1:13:01 - Error 409
- [ ] (54) 1:13:01 - (No mencionado) - No se está mostrando el # de salida. Mostrarlo, y confirmar con Analista y Almacén si la salida por Bodega tiene un consecutivo específico

**Comment by AlexFBP** [comment]
Issues creados a partir de las dos revisiones
